import unittest

from day08 import parse_lines, part_one, part_two


class TestDay08(unittest.TestCase):
    example = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

    def test_parse_lines(self):
        parse_lines(self.example.splitlines())

    def test_part_one(self):
        result = part_one(self.example.splitlines())
        self.assertEqual(result, 14)

    def test_part_two(self):
        result = part_two(self.example.splitlines())
        self.assertEqual(result, 34)


if __name__ == "__main__":
    unittest.main()
